services:
  - type: web
    name: rexify-bot
    env: node
    plan: standard
    buildCommand: npm install && npx puppeteer install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache
      - key: NODE_ENV
        value: production
